name: Deploy to WebVM with Tailscale

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh  # Install Tailscale
        sudo apt-get install tailscale  # Ensure it's installed

    - name: Start Tailscale daemon
      run: |
        sudo tailscaled &
        sleep 5  # Wait for the Tailscale daemon to start

    - name: Authenticate with Tailscale
      run: |
        sudo tailscale up --auth-key=tskey-auth-ksaETTy8Bu11CNTRL-11F2jToXexdaUmCB78zBxdshyRjWPgQL --hostname=webvm-deployer  # Hardcoded auth key
        sudo tailscale status  # Check if Tailscale is connected successfully

    - name: check for hello.ts.net in netmap
      run: |
        tailscale status | grep -q hello  # Check the status

    - name: Deploy FastAPI application
      run: |
        # Replace with your deployment commands for FastAPI (e.g., Git pull, migration, etc.)
        echo "Deploying FastAPI app..."
        # Example: python app.py or docker commands, depending on your setup

    - name: Post-deploy status check
      run: |
        echo "Post deployment checks"
        sudo tailscale status  # Verify Tailscale status post-deployment

    - name: Cleanup
      run: |
        sudo pkill tailscaled  # Stop the Tailscale daemon if no longer needed
